[package]
name = "{{project-name}}"
description = "Template for starting a reView project using Trunk"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
review = "0.1.0"
